### ISSUE TITLE
Issues with Digispark setup. Link cable to MIDI (5-pin)

### ISSUE THREAD

**Issue by hiddenindians** [frederickk/PocketMidiLink#1]
Hi, I've followed the guide and flashed the build.sh successfully but I can't seem to get the cable to work. 

When I hit play from my midi device, nanoloop doesn't respond. The LEDs on the digispark stay lit up. 

If I hit play from Nanoloop, the LEDs blink to the BPM set in Nanoloop. As expected, nothing happens on the MIDI device. 

Any idea what might be going on? I've checked continuity for all connections.

**Comment by hiddenindians** [comment]
Please disregard this issue. I had followed the diagram in the readme assuming that they represented the pinouts for the cables instead of the ports. Mirroring my wiring fixed the issue.

**Comment by frederickk** [comment]
@hiddenindians glad to hear you sorted it out. My diagram is a little cryptic, at some point I'll redraw it for clarity. Happy music making!
